### ISSUE TITLE
What are the differences between raw regulons and processed regulons?

### ISSUE THREAD

**Issue by feather-W** [saezlab/CollecTRI#13]
Hi, 

I found that there are raw regulons and processed regulons, the **processed regulons** can be loaded through "**decoupleR::get_collectri(organism='human', split_complexes=FALSE)**" and the **raw  regulons** can be loaded through "**OmnipathR::collectri(organism=9606L, genesymbols=TRUE, loops=TRUE)**".

I wonder if there are some differences between these two datasets? Such as the different number of TFs, regulons, and so on.

Best

**Comment by PauBadiaM** [comment]
Hi @feather-W ,

the function `OmnipathR::collectri` returns the available raw unprocessed data in case you want to use it to build a your own GRN in a different manner for example.

Alternatively, the function [`decoupleR::get_collectri`](https://github.com/saezlab/decoupleR/blob/master/R/utils-omnipath.R#L92), processes these data (as stated in the method's section of the [publication](https://academic.oup.com/nar/article/51/20/10934/7318114?login=true#424820335)) to have them ready to use for TF enrichment analysis in `decoupleR`.

The main difference between them is the sign assignment (+ or -) and whether TF complexes where keep together or separated into individual entities (with the param `split_complexes` in the `decoupleR` function).

Hope this is helpful!

**Comment by feather-W** [comment]
Hi PauBadiaM,

Thanks for your reply very much! And I got it.

Best
