### ISSUE TITLE
problem with collectri package in R

### ISSUE THREAD

**Issue by annarerra** [saezlab/CollecTRI#16]
Hello, 

I was trying to reproduce the code from here https://saezlab.github.io/decoupleR/articles/tf_bk.html 
but I receive an error at this point 
![image](https://github.com/saezlab/CollecTRI/assets/74925521/8482ae9f-ecba-4e9b-85fd-94be9e1b2981)
The decoupleR package is already installed.

Could you please help me with this?

Thank you in advance :)

**Comment by PauBadiaM** [comment]
Hi @annarerra,

Try installing the latest versions for `decoupleR` and `OmnipathR`, restart the R session and try again:

```R
remotes::install_github('saezlab/decoupleR')
remotes::install_github('saezlab/OmnipathR')
```

Let me know how it goes!

**Comment by annarerra** [comment]
Hello Pau!

It worked! Thanks a lot!
