### ISSUE TITLE
commercial use of collectri

### ISSUE THREAD

**Issue by annarerra** [saezlab/CollecTRI#17]
Hello,

First of all, thank you for developing this nice tool!
I am working at a company and we would like to use collectri for our analyses.
I checked the licenses of the included tools and I found out that the SIGNOR is not allowed to be used commercially.
Is there a way to remove this package when using collectri and continue with the rest?

Thank you for your help :)

**Comment by PauBadiaM** [comment]
Hi @annarerra,

Luckily SIGNOR recently made changes to their license which allows commercial use (check https://github.com/saezlab/CollecTRI/issues/15#issuecomment-2075199876), so there is no need to remove it anymore.

**Comment by annarerra** [comment]
That's great!
And what about DorothEA? You are using a version here which is called DorothEA A (Pazar - LGPLv3 , ORegAnno -LGPLv3, HTRIdb -LGPLv3, SIGNOR -CC BY 4.0 , DoRothEA-reviews - CC BY 4.0). 
There are no restrictions, right?

Thank you :)

**Comment by smuellerd** [comment]
Hi @annarerra,

yes exactly. CollecTRI only includes interactions from DoRothEA's confidence level A which have no restrictions.
