### ISSUE TITLE
CollecTRI interaction confidence level and reference retrieval

### ISSUE THREAD

**Issue by Sophon-0** [saezlab/CollecTRI#18]
CollecTRI interactions were included if there is a at least a reference/manuscript proving that such regulatory interaction exists (in a given biological context). In the case of old dorothea, such interactions belonged only to class A. 

By importing collectri directly from omnipath: https://github.com/saezlab/decoupler-py/blob/main/decoupler/omnip.py#L523
you can get a data frame with the method it was found (manually curated, text mining, or existing databases...). This returns a dataframe containing from which sources each interaction comes (column source).

**Comment by smuellerd** [comment]
Hi @Sophon-0,

we also added this feature to the newest decoupler version in R: https://github.com/saezlab/decoupleR/blob/8716d1a7f0296310aa2c62d3e017dfdb0e4f45f3/R/utils-omnipath.R#L95. 

If you now run `get_collectri(organism='human', split_complexes=FALSE, load_meta=TRUE)` and set the load_meta to TRUE you will also get the information about the references, the databases, the sign decision and the TF class for each TF-gene link.

Best
Sophia
