### ISSUE TITLE
OmnipathR::collectri(organism=9606L, genesymbols=TRUE, loops=TRUE) ERROR 

### ISSUE THREAD

**Issue by LorNic97** [saezlab/CollecTRI#22]
Hi Saezlab,
Thanks for your precious work and for developing this tool! 
Unfortunately when I follow this command:

`OmnipathR::collectri(organism=9606L, genesymbols=TRUE, loops=TRUE)`

I get this error: 
Error in `map_int()`:
ℹ In index: 1.
Caused by error in `map_int()`:
ℹ In index: 1.
Caused by error in `full_join()`:
! Can't join `x$ncbi_tax_id` with `y$ncbi_tax_id` due to incompatible types.
ℹ `x$ncbi_tax_id` is a <integer>.
ℹ `y$ncbi_tax_id` is a <character>.

Could you help me solve this issue?
Thanks in advance!

**Comment by deeenes** [comment]
Hi @LorNic97, I have the suspicion this error is related to [this one](https://github.com/saezlab/CollecTRI/issues/21). I'd recommend you to try a similar solution: reinstall OmnipathR, and try the download with an empty cache:

```
library(remotes)
remotes::install_github('saezlab/OmnipathR')
```

In a new R session:

```
library(OmnipathR)

tmpcache <- tempdir()
omnipath_set_cachedir(tmpcache)
omnipath_set_console_loglevel('trace')

ci <- collectri(organism=9606L, genesymbols=TRUE, loops=TRUE)
```

If it works, in a new R session wipe the OmniPath cache of your user:

```
library(OmnipathR)

omnipath_cache_wipe()
```

If the error appears also with the updated package and empty cache, please share the traceback and the log:

```
library(OmnipathR)

ci <- collectri(organism=9606L, genesymbols=TRUE, loops=TRUE)
# error happens

traceback()

omnipath_log()
# or call omnipath_logfile() for the path
```

**Comment by LorNic97** [comment]
Thank you very much, it worked!
