### ISSUE TITLE
Where can I find the CollecTRI rda file or data file for consumption when not working with R or Python?

### ISSUE THREAD

**Issue by pcm32** [saezlab/CollecTRI#7]
Thanks!

**Comment by smuellerd** [comment]
Hi @pcm32,

thanks for your interest in CollecTRI. We currently do not provide a static file of CollecTRI as it is more convenient to update any modifications though its implementation within OmniPath (which can be accessed through Omnipath directly or through decoupler and DoRothEA). However, we are planning to include a CSV file in our upcoming Zenodo release next month. I will make sure to provide the link to the file as soon as it becomes available.

Best regards
Sophia

**Comment by smuellerd** [comment]
Hi @pcm32,

the latest version of the CollecTRI regulons is now available for download in our Zenodo release: https://zenodo.org/record/8192729/files/CollecTRI_regulons.csv?download=1.

I hope this will be helpful!

Best regards
Sophia
